/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppAdapter {}
  interface AppBridge {}
  interface AppChain {}
  interface AppCommand {}
  interface AppDecorator {}
  interface AppFacade {}
  interface AppFactory {}
  interface AppFlyweight {}
  interface AppHome {}
  interface AppIterator {}
  interface AppMediator {}
  interface AppMemento {}
  interface AppObserver {}
  interface AppProxy {}
  interface AppRoot {}
  interface AppSingleton {}
  interface AppState {}
  interface AppState2 {}
  interface AppStrategy {}
  interface AppTemplate {}
  interface PatternPhotos {
    'cl': string;
    'cl2': string;
    'imp': string;
    'imp2': string;
    'uml': string;
    'uml2': string;
  }
}

declare global {


  interface HTMLAppAdapterElement extends Components.AppAdapter, HTMLStencilElement {}
  var HTMLAppAdapterElement: {
    prototype: HTMLAppAdapterElement;
    new (): HTMLAppAdapterElement;
  };

  interface HTMLAppBridgeElement extends Components.AppBridge, HTMLStencilElement {}
  var HTMLAppBridgeElement: {
    prototype: HTMLAppBridgeElement;
    new (): HTMLAppBridgeElement;
  };

  interface HTMLAppChainElement extends Components.AppChain, HTMLStencilElement {}
  var HTMLAppChainElement: {
    prototype: HTMLAppChainElement;
    new (): HTMLAppChainElement;
  };

  interface HTMLAppCommandElement extends Components.AppCommand, HTMLStencilElement {}
  var HTMLAppCommandElement: {
    prototype: HTMLAppCommandElement;
    new (): HTMLAppCommandElement;
  };

  interface HTMLAppDecoratorElement extends Components.AppDecorator, HTMLStencilElement {}
  var HTMLAppDecoratorElement: {
    prototype: HTMLAppDecoratorElement;
    new (): HTMLAppDecoratorElement;
  };

  interface HTMLAppFacadeElement extends Components.AppFacade, HTMLStencilElement {}
  var HTMLAppFacadeElement: {
    prototype: HTMLAppFacadeElement;
    new (): HTMLAppFacadeElement;
  };

  interface HTMLAppFactoryElement extends Components.AppFactory, HTMLStencilElement {}
  var HTMLAppFactoryElement: {
    prototype: HTMLAppFactoryElement;
    new (): HTMLAppFactoryElement;
  };

  interface HTMLAppFlyweightElement extends Components.AppFlyweight, HTMLStencilElement {}
  var HTMLAppFlyweightElement: {
    prototype: HTMLAppFlyweightElement;
    new (): HTMLAppFlyweightElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppIteratorElement extends Components.AppIterator, HTMLStencilElement {}
  var HTMLAppIteratorElement: {
    prototype: HTMLAppIteratorElement;
    new (): HTMLAppIteratorElement;
  };

  interface HTMLAppMediatorElement extends Components.AppMediator, HTMLStencilElement {}
  var HTMLAppMediatorElement: {
    prototype: HTMLAppMediatorElement;
    new (): HTMLAppMediatorElement;
  };

  interface HTMLAppMementoElement extends Components.AppMemento, HTMLStencilElement {}
  var HTMLAppMementoElement: {
    prototype: HTMLAppMementoElement;
    new (): HTMLAppMementoElement;
  };

  interface HTMLAppObserverElement extends Components.AppObserver, HTMLStencilElement {}
  var HTMLAppObserverElement: {
    prototype: HTMLAppObserverElement;
    new (): HTMLAppObserverElement;
  };

  interface HTMLAppProxyElement extends Components.AppProxy, HTMLStencilElement {}
  var HTMLAppProxyElement: {
    prototype: HTMLAppProxyElement;
    new (): HTMLAppProxyElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSingletonElement extends Components.AppSingleton, HTMLStencilElement {}
  var HTMLAppSingletonElement: {
    prototype: HTMLAppSingletonElement;
    new (): HTMLAppSingletonElement;
  };

  interface HTMLAppStateElement extends Components.AppState, HTMLStencilElement {}
  var HTMLAppStateElement: {
    prototype: HTMLAppStateElement;
    new (): HTMLAppStateElement;
  };

  interface HTMLAppState2Element extends Components.AppState2, HTMLStencilElement {}
  var HTMLAppState2Element: {
    prototype: HTMLAppState2Element;
    new (): HTMLAppState2Element;
  };

  interface HTMLAppStrategyElement extends Components.AppStrategy, HTMLStencilElement {}
  var HTMLAppStrategyElement: {
    prototype: HTMLAppStrategyElement;
    new (): HTMLAppStrategyElement;
  };

  interface HTMLAppTemplateElement extends Components.AppTemplate, HTMLStencilElement {}
  var HTMLAppTemplateElement: {
    prototype: HTMLAppTemplateElement;
    new (): HTMLAppTemplateElement;
  };

  interface HTMLPatternPhotosElement extends Components.PatternPhotos, HTMLStencilElement {}
  var HTMLPatternPhotosElement: {
    prototype: HTMLPatternPhotosElement;
    new (): HTMLPatternPhotosElement;
  };
  interface HTMLElementTagNameMap {
    'app-adapter': HTMLAppAdapterElement;
    'app-bridge': HTMLAppBridgeElement;
    'app-chain': HTMLAppChainElement;
    'app-command': HTMLAppCommandElement;
    'app-decorator': HTMLAppDecoratorElement;
    'app-facade': HTMLAppFacadeElement;
    'app-factory': HTMLAppFactoryElement;
    'app-flyweight': HTMLAppFlyweightElement;
    'app-home': HTMLAppHomeElement;
    'app-iterator': HTMLAppIteratorElement;
    'app-mediator': HTMLAppMediatorElement;
    'app-memento': HTMLAppMementoElement;
    'app-observer': HTMLAppObserverElement;
    'app-proxy': HTMLAppProxyElement;
    'app-root': HTMLAppRootElement;
    'app-singleton': HTMLAppSingletonElement;
    'app-state': HTMLAppStateElement;
    'app-state2': HTMLAppState2Element;
    'app-strategy': HTMLAppStrategyElement;
    'app-template': HTMLAppTemplateElement;
    'pattern-photos': HTMLPatternPhotosElement;
  }
}

declare namespace LocalJSX {
  interface AppAdapter {}
  interface AppBridge {}
  interface AppChain {}
  interface AppCommand {}
  interface AppDecorator {}
  interface AppFacade {}
  interface AppFactory {}
  interface AppFlyweight {}
  interface AppHome {}
  interface AppIterator {}
  interface AppMediator {}
  interface AppMemento {}
  interface AppObserver {}
  interface AppProxy {}
  interface AppRoot {}
  interface AppSingleton {}
  interface AppState {}
  interface AppState2 {}
  interface AppStrategy {}
  interface AppTemplate {}
  interface PatternPhotos {
    'cl'?: string;
    'cl2'?: string;
    'imp'?: string;
    'imp2'?: string;
    'uml'?: string;
    'uml2'?: string;
  }

  interface IntrinsicElements {
    'app-adapter': AppAdapter;
    'app-bridge': AppBridge;
    'app-chain': AppChain;
    'app-command': AppCommand;
    'app-decorator': AppDecorator;
    'app-facade': AppFacade;
    'app-factory': AppFactory;
    'app-flyweight': AppFlyweight;
    'app-home': AppHome;
    'app-iterator': AppIterator;
    'app-mediator': AppMediator;
    'app-memento': AppMemento;
    'app-observer': AppObserver;
    'app-proxy': AppProxy;
    'app-root': AppRoot;
    'app-singleton': AppSingleton;
    'app-state': AppState;
    'app-state2': AppState2;
    'app-strategy': AppStrategy;
    'app-template': AppTemplate;
    'pattern-photos': PatternPhotos;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-adapter': LocalJSX.AppAdapter & JSXBase.HTMLAttributes<HTMLAppAdapterElement>;
      'app-bridge': LocalJSX.AppBridge & JSXBase.HTMLAttributes<HTMLAppBridgeElement>;
      'app-chain': LocalJSX.AppChain & JSXBase.HTMLAttributes<HTMLAppChainElement>;
      'app-command': LocalJSX.AppCommand & JSXBase.HTMLAttributes<HTMLAppCommandElement>;
      'app-decorator': LocalJSX.AppDecorator & JSXBase.HTMLAttributes<HTMLAppDecoratorElement>;
      'app-facade': LocalJSX.AppFacade & JSXBase.HTMLAttributes<HTMLAppFacadeElement>;
      'app-factory': LocalJSX.AppFactory & JSXBase.HTMLAttributes<HTMLAppFactoryElement>;
      'app-flyweight': LocalJSX.AppFlyweight & JSXBase.HTMLAttributes<HTMLAppFlyweightElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-iterator': LocalJSX.AppIterator & JSXBase.HTMLAttributes<HTMLAppIteratorElement>;
      'app-mediator': LocalJSX.AppMediator & JSXBase.HTMLAttributes<HTMLAppMediatorElement>;
      'app-memento': LocalJSX.AppMemento & JSXBase.HTMLAttributes<HTMLAppMementoElement>;
      'app-observer': LocalJSX.AppObserver & JSXBase.HTMLAttributes<HTMLAppObserverElement>;
      'app-proxy': LocalJSX.AppProxy & JSXBase.HTMLAttributes<HTMLAppProxyElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'app-singleton': LocalJSX.AppSingleton & JSXBase.HTMLAttributes<HTMLAppSingletonElement>;
      'app-state': LocalJSX.AppState & JSXBase.HTMLAttributes<HTMLAppStateElement>;
      'app-state2': LocalJSX.AppState2 & JSXBase.HTMLAttributes<HTMLAppState2Element>;
      'app-strategy': LocalJSX.AppStrategy & JSXBase.HTMLAttributes<HTMLAppStrategyElement>;
      'app-template': LocalJSX.AppTemplate & JSXBase.HTMLAttributes<HTMLAppTemplateElement>;
      'pattern-photos': LocalJSX.PatternPhotos & JSXBase.HTMLAttributes<HTMLPatternPhotosElement>;
    }
  }
}


